In [150]:
import pandas as pd 
import numpy as np

In [151]:
import pandas as pd

dummy_data = {
    "review_text": [
        "I absolutely love this product, works flawlessly every time.",
        "The item arrived late and the packaging was damaged.",
        "Decent quality for the price, nothing extraordinary though.",
        "This is by far the best purchase I've made this year.",
        "Terrible experience, the product stopped working in two days.",
        "Good value for money, does what it claims.",
        "Not impressed, expected better build quality.",
        "Customer support was very helpful and responsive.",
        "The product is okay, but shipping took too long.",
        "Amazing! Exceeded all my expectations.",
        "Waste of money, completely useless.",
        "Pretty good overall, would recommend to friends.",
        "The design is sleek and modern, I like it.",
        "Stopped working after a week, very disappointed.",
        "Works as described, satisfied with the purchase.",
        "Packaging was poor, item slightly damaged.",
        "Excellent quality, worth every penny.",
        "Not bad, but there are better alternatives.",
        "Very happy with the performance.",
        "The instructions were confusing and unclear.",
        "Top-notch product, will definitely buy again.",
        "It’s okay, not great but not terrible either.",
        "Horrible, do not buy this product.",
        "Delivery was quick and product works fine.",
        "I regret buying this, not worth it.",
        "Fantastic build quality and great usability.",
        "Mediocre experience, nothing special.",
        "Really impressed with how well it works.",
        "Product is average, does the basic job.",
        "Very poor quality, broke within days.",
        "Loved it! Exactly what I was looking for.",
        "Not satisfied, performance issues observed.",
        "Works fine but feels a bit overpriced.",
        "Absolutely terrible, complete waste.",
        "Nice product, but could be improved.",
        "Highly recommend this to everyone.",
        "Disappointed with the durability.",
        "Everything works perfectly, no complaints.",
        "It’s fine for occasional use.",
        "Bad quality, not as described.",
        "Superb performance, exceeded expectations.",
        "The material feels cheap and flimsy.",
        "Very reliable and easy to use.",
        "Not worth the hype.",
        "Great product, fast delivery.",
        "Average quality, acceptable performance.",
        "Worst purchase I’ve made recently.",
        "Really good, I’m satisfied.",
        "The product is defective, had to return it.",
        "Excellent, would definitely recommend."
    ],
    "sentiment": [
        "positive","negative","negative","positive","negative",
        "positive","negative","positive","negative","positive",
        "negative","positive","positive","negative","positive",
        "negative","positive","positive","positive","negative",
        "positive","positive","negative","positive","negative",
        "positive","positive","positive","positive","negative",
        "positive","negative","positive","negative","negative",
        "positive","negative","positive","negative","negative",
        "positive","negative","positive","negative","positive",
        "negative","negative","positive","negative","positive"
    ]
}

df = pd.DataFrame(dummy_data)
print(df.head())
print(len(df))  # 50

                                         review_text sentiment
0  I absolutely love this product, works flawless...  positive
1  The item arrived late and the packaging was da...  negative
2  Decent quality for the price, nothing extraord...  negative
3  This is by far the best purchase I've made thi...  positive
4  Terrible experience, the product stopped worki...  negative
50

In [152]:
df["review_text"] = df["review_text"].str.lower()

In [153]:
df

                                          review_text sentiment
0   i absolutely love this product, works flawless...  positive
1   the item arrived late and the packaging was da...  negative
2   decent quality for the price, nothing extraord...  negative
3   this is by far the best purchase i've made thi...  positive
4   terrible experience, the product stopped worki...  negative
5          good value for money, does what it claims.  positive
6       not impressed, expected better build quality.  negative
7   customer support was very helpful and responsive.  positive
8    the product is okay, but shipping took too long.  negative
9              amazing! exceeded all my expectations.  positive
10                waste of money, completely useless.  negative
11   pretty good overall, would recommend to friends.  positive
12         the design is sleek and modern, i like it.  positive
13   stopped working after a week, very disappointed.  negative
14   works as described, satisfied with the purchase.  positive
15         packaging was poor, item slightly damaged.  negative
16              excellent quality, worth every penny.  positive
17        not bad, but there are better alternatives.  positive
18                   very happy with the performance.  positive
19       the instructions were confusing and unclear.  negative
20      top-notch product, will definitely buy again.  positive
21      it’s okay, not great but not terrible either.  positive
22                 horrible, do not buy this product.  negative
23         delivery was quick and product works fine.  positive
24                i regret buying this, not worth it.  negative
25       fantastic build quality and great usability.  positive
26              mediocre experience, nothing special.  positive
27           really impressed with how well it works.  positive
28            product is average, does the basic job.  positive
29              very poor quality, broke within days.  negative
30          loved it! exactly what i was looking for.  positive
31        not satisfied, performance issues observed.  negative
32             works fine but feels a bit overpriced.  positive
33               absolutely terrible, complete waste.  negative
34               nice product, but could be improved.  negative
35                 highly recommend this to everyone.  positive
36                  disappointed with the durability.  negative
37         everything works perfectly, no complaints.  positive
38                      it’s fine for occasional use.  negative
39                     bad quality, not as described.  negative
40         superb performance, exceeded expectations.  positive
41               the material feels cheap and flimsy.  negative
42                     very reliable and easy to use.  positive
43                                not worth the hype.  negative
44                      great product, fast delivery.  positive
45           average quality, acceptable performance.  negative
46                 worst purchase i’ve made recently.  negative
47                        really good, i’m satisfied.  positive
48        the product is defective, had to return it.  negative
49             excellent, would definitely recommend.  positive

In [154]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [155]:
docs = df["review_text"].apply(lambda x: nlp(x))

In [156]:
docs

0     (i, absolutely, love, this, product, ,, works,...
1     (the, item, arrived, late, and, the, packaging...
2     (decent, quality, for, the, price, ,, nothing,...
3     (this, is, by, far, the, best, purchase, i, 'v...
4     (terrible, experience, ,, the, product, stoppe...
5     (good, value, for, money, ,, does, what, it, c...
6     (not, impressed, ,, expected, better, build, q...
7     (customer, support, was, very, helpful, and, r...
8     (the, product, is, okay, ,, but, shipping, too...
9      (amazing, !, exceeded, all, my, expectations, .)
10        (waste, of, money, ,, completely, useless, .)
11    (pretty, good, overall, ,, would, recommend, t...
12    (the, design, is, sleek, and, modern, ,, i, li...
13    (stopped, working, after, a, week, ,, very, di...
14    (works, as, described, ,, satisfied, with, the...
15    (packaging, was, poor, ,, item, slightly, dama...
16      (excellent, quality, ,, worth, every, penny, .)
17    (not, bad, ,, but, there, are, better, alterna...
18             (very, happy, with, the, performance, .)
19    (the, instructions, were, confusing, and, uncl...
20    (top, -, notch, product, ,, will, definitely, ...
21    (it, ’s, okay, ,, not, great, but, not, terrib...
22        (horrible, ,, do, not, buy, this, product, .)
23    (delivery, was, quick, and, product, works, fi...
24      (i, regret, buying, this, ,, not, worth, it, .)
25    (fantastic, build, quality, and, great, usabil...
26       (mediocre, experience, ,, nothing, special, .)
27    (really, impressed, with, how, well, it, works...
28    (product, is, average, ,, does, the, basic, jo...
29     (very, poor, quality, ,, broke, within, days, .)
30    (loved, it, !, exactly, what, i, was, looking,...
31    (not, satisfied, ,, performance, issues, obser...
32     (works, fine, but, feels, a, bit, overpriced, .)
33        (absolutely, terrible, ,, complete, waste, .)
34      (nice, product, ,, but, could, be, improved, .)
35           (highly, recommend, this, to, everyone, .)
36             (disappointed, with, the, durability, .)
37    (everything, works, perfectly, ,, no, complain...
38              (it, ’s, fine, for, occasional, use, .)
39             (bad, quality, ,, not, as, described, .)
40    (superb, performance, ,, exceeded, expectation...
41        (the, material, feels, cheap, and, flimsy, .)
42              (very, reliable, and, easy, to, use, .)
43                           (not, worth, the, hype, .)
44               (great, product, ,, fast, delivery, .)
45    (average, quality, ,, acceptable, performance, .)
46         (worst, purchase, i, ’ve, made, recently, .)
47               (really, good, ,, i, ’m, satisfied, .)
48    (the, product, is, defective, ,, had, to, retu...
49      (excellent, ,, would, definitely, recommend, .)
Name: review_text, dtype: object

In [157]:
# We apply the spacy pipeline and the list comprehension row by row
df["clean_tokens"] = df["review_text"].apply(
    lambda x: [token.text.lower() for token in nlp(x) if not token.is_punct and not token.is_stop]
)

print(df[["review_text", "clean_tokens"]])

                                          review_text  \
0   i absolutely love this product, works flawless...
1   the item arrived late and the packaging was da...
2   decent quality for the price, nothing extraord...
3   this is by far the best purchase i've made thi...
4   terrible experience, the product stopped worki...
5          good value for money, does what it claims.
6       not impressed, expected better build quality.
7   customer support was very helpful and responsive.
8    the product is okay, but shipping took too long.
9              amazing! exceeded all my expectations.
10                waste of money, completely useless.
11   pretty good overall, would recommend to friends.
12         the design is sleek and modern, i like it.
13   stopped working after a week, very disappointed.
14   works as described, satisfied with the purchase.
15         packaging was poor, item slightly damaged.
16              excellent quality, worth every penny.
17        not bad, but there are better alternatives.
18                   very happy with the performance.
19       the instructions were confusing and unclear.
20      top-notch product, will definitely buy again.
21      it’s okay, not great but not terrible either.
22                 horrible, do not buy this product.
23         delivery was quick and product works fine.
24                i regret buying this, not worth it.
25       fantastic build quality and great usability.
26              mediocre experience, nothing special.
27           really impressed with how well it works.
28            product is average, does the basic job.
29              very poor quality, broke within days.
30          loved it! exactly what i was looking for.
31        not satisfied, performance issues observed.
32             works fine but feels a bit overpriced.
33               absolutely terrible, complete waste.
34               nice product, but could be improved.
35                 highly recommend this to everyone.
36                  disappointed with the durability.
37         everything works perfectly, no complaints.
38                      it’s fine for occasional use.
39                     bad quality, not as described.
40         superb performance, exceeded expectations.
41               the material feels cheap and flimsy.
42                     very reliable and easy to use.
43                                not worth the hype.
44                      great product, fast delivery.
45           average quality, acceptable performance.
46                 worst purchase i’ve made recently.
47                        really good, i’m satisfied.
48        the product is defective, had to return it.
49             excellent, would definitely recommend.

                                         clean_tokens
0   [absolutely, love, product, works, flawlessly,...
1           [item, arrived, late, packaging, damaged]
2             [decent, quality, price, extraordinary]
3                         [far, best, purchase, year]
4   [terrible, experience, product, stopped, worki...
5                        [good, value, money, claims]
6       [impressed, expected, better, build, quality]
7            [customer, support, helpful, responsive]
8               [product, okay, shipping, took, long]
9                   [amazing, exceeded, expectations]
10                [waste, money, completely, useless]
11        [pretty, good, overall, recommend, friends]
12                      [design, sleek, modern, like]
13             [stopped, working, week, disappointed]
14            [works, described, satisfied, purchase]
15         [packaging, poor, item, slightly, damaged]
16                 [excellent, quality, worth, penny]
17                        [bad, better, alternatives]
18                               [happy, performance]
19                 [instructions, confusing, unclear]
20                  [notch, product, definitely, buy]
21                            [okay, great, terrible]
22                           [horrible, buy, product]
23            [delivery, quick, product, works, fine]
24                            [regret, buying, worth]
25      [fantastic, build, quality, great, usability]
26                    [mediocre, experience, special]
27                                 [impressed, works]
28                     [product, average, basic, job]
29                       [poor, quality, broke, days]
30                          [loved, exactly, looking]
31         [satisfied, performance, issues, observed]
32              [works, fine, feels, bit, overpriced]
33            [absolutely, terrible, complete, waste]
34                          [nice, product, improved]
35                                [highly, recommend]
36                         [disappointed, durability]
37                     [works, perfectly, complaints]
38                            [fine, occasional, use]
39                          [bad, quality, described]
40      [superb, performance, exceeded, expectations]
41                   [material, feels, cheap, flimsy]
42                              [reliable, easy, use]
43                                      [worth, hype]
44                   [great, product, fast, delivery]
45        [average, quality, acceptable, performance]
46                        [worst, purchase, recently]
47                                  [good, satisfied]
48                       [product, defective, return]
49                 [excellent, definitely, recommend]

In [158]:
df["clean_tokens"]

0     [absolutely, love, product, works, flawlessly,...
1             [item, arrived, late, packaging, damaged]
2               [decent, quality, price, extraordinary]
3                           [far, best, purchase, year]
4     [terrible, experience, product, stopped, worki...
5                          [good, value, money, claims]
6         [impressed, expected, better, build, quality]
7              [customer, support, helpful, responsive]
8                 [product, okay, shipping, took, long]
9                     [amazing, exceeded, expectations]
10                  [waste, money, completely, useless]
11          [pretty, good, overall, recommend, friends]
12                        [design, sleek, modern, like]
13               [stopped, working, week, disappointed]
14              [works, described, satisfied, purchase]
15           [packaging, poor, item, slightly, damaged]
16                   [excellent, quality, worth, penny]
17                          [bad, better, alternatives]
18                                 [happy, performance]
19                   [instructions, confusing, unclear]
20                    [notch, product, definitely, buy]
21                              [okay, great, terrible]
22                             [horrible, buy, product]
23              [delivery, quick, product, works, fine]
24                              [regret, buying, worth]
25        [fantastic, build, quality, great, usability]
26                      [mediocre, experience, special]
27                                   [impressed, works]
28                       [product, average, basic, job]
29                         [poor, quality, broke, days]
30                            [loved, exactly, looking]
31           [satisfied, performance, issues, observed]
32                [works, fine, feels, bit, overpriced]
33              [absolutely, terrible, complete, waste]
34                            [nice, product, improved]
35                                  [highly, recommend]
36                           [disappointed, durability]
37                       [works, perfectly, complaints]
38                              [fine, occasional, use]
39                            [bad, quality, described]
40        [superb, performance, exceeded, expectations]
41                     [material, feels, cheap, flimsy]
42                                [reliable, easy, use]
43                                        [worth, hype]
44                     [great, product, fast, delivery]
45          [average, quality, acceptable, performance]
46                          [worst, purchase, recently]
47                                    [good, satisfied]
48                         [product, defective, return]
49                   [excellent, definitely, recommend]
Name: clean_tokens, dtype: object

In [159]:
df["clean_tokens"].apply(lambda x: " ".join(x))

0        absolutely love product works flawlessly time
1                  item arrived late packaging damaged
2                   decent quality price extraordinary
3                               far best purchase year
4     terrible experience product stopped working days
5                              good value money claims
6              impressed expected better build quality
7                  customer support helpful responsive
8                      product okay shipping took long
9                        amazing exceeded expectations
10                      waste money completely useless
11               pretty good overall recommend friends
12                            design sleek modern like
13                   stopped working week disappointed
14                  works described satisfied purchase
15                packaging poor item slightly damaged
16                       excellent quality worth penny
17                             bad better alternatives
18                                   happy performance
19                      instructions confusing unclear
20                        notch product definitely buy
21                                 okay great terrible
22                                horrible buy product
23                   delivery quick product works fine
24                                 regret buying worth
25             fantastic build quality great usability
26                         mediocre experience special
27                                     impressed works
28                           product average basic job
29                             poor quality broke days
30                               loved exactly looking
31               satisfied performance issues observed
32                     works fine feels bit overpriced
33                  absolutely terrible complete waste
34                               nice product improved
35                                    highly recommend
36                             disappointed durability
37                          works perfectly complaints
38                                 fine occasional use
39                               bad quality described
40            superb performance exceeded expectations
41                         material feels cheap flimsy
42                                   reliable easy use
43                                          worth hype
44                         great product fast delivery
45              average quality acceptable performance
46                             worst purchase recently
47                                      good satisfied
48                            product defective return
49                      excellent definitely recommend
Name: clean_tokens, dtype: str

In [160]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

In [161]:
bow_matrix = count_vectorizer.fit_transform(df["clean_tokens"].apply(lambda x: " ".join(x)))

In [162]:
vocab = count_vectorizer.get_feature_names_out()

In [163]:
vocab

array(['absolutely', 'acceptable', 'alternatives', 'amazing', 'arrived',
       'average', 'bad', 'basic', 'best', 'better', 'bit', 'broke',
       'build', 'buy', 'buying', 'cheap', 'claims', 'complaints',
       'complete', 'completely', 'confusing', 'customer', 'damaged',
       'days', 'decent', 'defective', 'definitely', 'delivery',
       'described', 'design', 'disappointed', 'durability', 'easy',
       'exactly', 'exceeded', 'excellent', 'expectations', 'expected',
       'experience', 'extraordinary', 'fantastic', 'far', 'fast', 'feels',
       'fine', 'flawlessly', 'flimsy', 'friends', 'good', 'great',
       'happy', 'helpful', 'highly', 'horrible', 'hype', 'impressed',
       'improved', 'instructions', 'issues', 'item', 'job', 'late',
       'like', 'long', 'looking', 'love', 'loved', 'material', 'mediocre',
       'modern', 'money', 'nice', 'notch', 'observed', 'occasional',
       'okay', 'overall', 'overpriced', 'packaging', 'penny', 'perfectly',
       'performance', 'poor', 'pretty', 'price', 'product', 'purchase',
       'quality', 'quick', 'recently', 'recommend', 'regret', 'reliable',
       'responsive', 'return', 'satisfied', 'shipping', 'sleek',
       'slightly', 'special', 'stopped', 'superb', 'support', 'terrible',
       'time', 'took', 'unclear', 'usability', 'use', 'useless', 'value',
       'waste', 'week', 'working', 'works', 'worst', 'worth', 'year'],
      dtype=object)

In [164]:
len(vocab)

118

In [165]:
bow_matrix.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [166]:
counts = np.sum(bow_matrix.toarray(), axis=0)

In [167]:
word_count_def = pd.DataFrame({"word": vocab, "count": counts})

In [168]:
top_words = word_count_def.sort_values(by="count", ascending=False)

In [169]:
top_words

             word  count
85        product     10
87        quality      7
114         works      6
81    performance      4
95      satisfied      3
..            ...    ...
1      acceptable      1
58         issues      1
57   instructions      1
56       improved      1
117          year      1

[118 rows x 2 columns]

In [170]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [171]:
onehotencoder = OneHotEncoder(sparse_output=False)

array_of_words = list(df["clean_tokens"])

In [172]:
array_of_words

[['absolutely', 'love', 'product', 'works', 'flawlessly', 'time'],
 ['item', 'arrived', 'late', 'packaging', 'damaged'],
 ['decent', 'quality', 'price', 'extraordinary'],
 ['far', 'best', 'purchase', 'year'],
 ['terrible', 'experience', 'product', 'stopped', 'working', 'days'],
 ['good', 'value', 'money', 'claims'],
 ['impressed', 'expected', 'better', 'build', 'quality'],
 ['customer', 'support', 'helpful', 'responsive'],
 ['product', 'okay', 'shipping', 'took', 'long'],
 ['amazing', 'exceeded', 'expectations'],
 ['waste', 'money', 'completely', 'useless'],
 ['pretty', 'good', 'overall', 'recommend', 'friends'],
 ['design', 'sleek', 'modern', 'like'],
 ['stopped', 'working', 'week', 'disappointed'],
 ['works', 'described', 'satisfied', 'purchase'],
 ['packaging', 'poor', 'item', 'slightly', 'damaged'],
 ['excellent', 'quality', 'worth', 'penny'],
 ['bad', 'better', 'alternatives'],
 ['happy', 'performance'],
 ['instructions', 'confusing', 'unclear'],
 ['notch', 'product', 'definitely', 'buy'],
 ['okay', 'great', 'terrible'],
 ['horrible', 'buy', 'product'],
 ['delivery', 'quick', 'product', 'works', 'fine'],
 ['regret', 'buying', 'worth'],
 ['fantastic', 'build', 'quality', 'great', 'usability'],
 ['mediocre', 'experience', 'special'],
 ['impressed', 'works'],
 ['product', 'average', 'basic', 'job'],
 ['poor', 'quality', 'broke', 'days'],
 ['loved', 'exactly', 'looking'],
 ['satisfied', 'performance', 'issues', 'observed'],
 ['works', 'fine', 'feels', 'bit', 'overpriced'],
 ['absolutely', 'terrible', 'complete', 'waste'],
 ['nice', 'product', 'improved'],
 ['highly', 'recommend'],
 ['disappointed', 'durability'],
 ['works', 'perfectly', 'complaints'],
 ['fine', 'occasional', 'use'],
 ['bad', 'quality', 'described'],
 ['superb', 'performance', 'exceeded', 'expectations'],
 ['material', 'feels', 'cheap', 'flimsy'],
 ['reliable', 'easy', 'use'],
 ['worth', 'hype'],
 ['great', 'product', 'fast', 'delivery'],
 ['average', 'quality', 'acceptable', 'performance'],
 ['worst', 'purchase', 'recently'],
 ['good', 'satisfied'],
 ['product', 'defective', 'return'],
 ['excellent', 'definitely', 'recommend']]

In [173]:
ohe_vectorizer = CountVectorizer(binary=True)

In [174]:
ohe_matrix = ohe_vectorizer.fit_transform(df["clean_tokens"].apply(lambda x: " ".join(x)))

In [175]:
ohe_matrix.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [176]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [177]:
tfidf = TfidfVectorizer()

In [178]:
tfidf_matrix = tfidf.fit_transform(df["clean_tokens"].apply(lambda x: " ".join(x)))

In [179]:
tfidf_matrix.toarray()

array([[0.41841422, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [180]:
bow_matrix.shape, ohe_matrix.shape, tfidf_matrix.shape

((50, 118), (50, 118), (50, 118))

In [181]:
#% of zeros in each matrix

def calculate_sparsity(matrix):
    total_elements = matrix.shape[0] * matrix.shape[1]
    non_zero_elements = matrix.count_nonzero()
    sparsity = (total_elements - non_zero_elements) / total_elements
    return sparsity

print("Sparsity of BoW matrix:", calculate_sparsity(bow_matrix))
print("Sparsity of One-Hot Encoding matrix:", calculate_sparsity(ohe_matrix))
print("Sparsity of TF-IDF matrix:", calculate_sparsity(tfidf_matrix))

Sparsity of BoW matrix: 0.968813559322034
Sparsity of One-Hot Encoding matrix: 0.968813559322034
Sparsity of TF-IDF matrix: 0.968813559322034

In [182]:
df["sentiment"] = df["sentiment"].map({"positive": 1, "negative": 0})

In [183]:
df

,review_text,sentiment,clean_tokens
0,"i absolutely love this product, works flawless...",1,"[absolutely, love, product, works, flawlessly,..."
1,the item arrived late and the packaging was da...,0,"[item, arrived, late, packaging, damaged]"
2,"decent quality for the price, nothing extraord...",0,"[decent, quality, price, extraordinary]"
3,this is by far the best purchase i've made thi...,1,"[far, best, purchase, year]"
4,"terrible experience, the product stopped worki...",0,"[terrible, experience, product, stopped, worki..."
5,"good value for money, does what it claims.",1,"[good, value, money, claims]"
6,"not impressed, expected better build quality.",0,"[impressed, expected, better, build, quality]"
7,customer support was very helpful and responsive.,1,"[customer, support, helpful, responsive]"
8,"the product is okay, but shipping took too long.",0,"[product, okay, shipping, took, long]"
9,amazing! exceeded all my expectations.,1,"[amazing, exceeded, expectations]"
10,"waste of money, completely useless.",0,"[waste, money, completely, useless]"
11,"pretty good overall, would recommend to friends.",1,"[pretty, good, overall, recommend, friends]"
12,"the design is sleek and modern, i like it.",1,"[design, sleek, modern, like]"
13,"stopped working after a week, very disappointed.",0,"[stopped, working, week, disappointed]"
14,"works as described, satisfied with the purchase.",1,"[works, described, satisfied, purchase]"
15,"packaging was poor, item slightly damaged.",0,"[packaging, poor, item, slightly, damaged]"
16,"excellent quality, worth every penny.",1,"[excellent, quality, worth, penny]"
17,"not bad, but there are better alternatives.",1,"[bad, better, alternatives]"
18,very happy with the performance.,1,"[happy, performance]"
19,the instructions were confusing and unclear.,0,"[instructions, confusing, unclear]"
20,"top-notch product, will definitely buy again.",1,"[notch, product, definitely, buy]"
21,"it’s okay, not great but not terrible either.",1,"[okay, great, terrible]"
22,"horrible, do not buy this product.",0,"[horrible, buy, product]"
23,delivery was quick and product works fine.,1,"[delivery, quick, product, works, fine]"
24,"i regret buying this, not worth it.",0,"[regret, buying, worth]"
25,fantastic build quality and great usability.,1,"[fantastic, build, quality, great, usability]"
26,"mediocre experience, nothing special.",1,"[mediocre, experience, special]"
27,really impressed with how well it works.,1,"[impressed, works]"
28,"product is average, does the basic job.",1,"[product, average, basic, job]"
29,"very poor quality, broke within days.",0,"[poor, quality, broke, days]"
30,loved it! exactly what i was looking for.,1,"[loved, exactly, looking]"
31,"not satisfied, performance issues observed.",0,"[satisfied, performance, issues, observed]"
32,works fine but feels a bit overpriced.,1,"[works, fine, feels, bit, overpriced]"
33,"absolutely terrible, complete waste.",0,"[absolutely, terrible, complete, waste]"
34,"nice product, but could be improved.",0,"[nice, product, improved]"
35,highly recommend this to everyone.,1,"[highly, recommend]"
36,disappointed with the durability.,0,"[disappointed, durability]"
37,"everything works perfectly, no complaints.",1,"[works, perfectly, complaints]"
38,it’s fine for occasional use.,0,"[fine, occasional, use]"
39,"bad quality, not as described.",0,"[bad, quality, described]"
40,"superb performance, exceeded expectations.",1,"[superb, performance, exceeded, expectations]"
41,the material feels cheap and flimsy.,0,"[material, feels, cheap, flimsy]"
42,very reliable and easy to use.,1,"[reliable, easy, use]"
43,not worth the hype.,0,"[worth, hype]"
44,"great product, fast delivery.",1,"[great, product, fast, delivery]"
45,"average quality, acceptable performance.",0,"[average, quality, acceptable, performance]"
46,worst purchase i’ve made recently.,0,"[worst, purchase, recently]"
47,"really good, i’m satisfied.",1,"[good, satisfied]"
48,"the product is defective, had to return it.",0,"[product, defective, return]"
49,"excellent, would definitely recommend.",1,"[excellent, definitely, recommend]"

In [184]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X = bow_matrix.toarray()  # Convert sparse matrix to dense array
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [185]:
predict = model.predict(X_test)

accuracy = model.score(X_test, y_test)

final_score = accuracy_score(y_test, model.predict(X_test))

In [186]:
print("Accuracy:", accuracy)
print("Final Score:", final_score)
print("Classification Report:\n", classification_report(y_test, model.predict(X_test)))

Accuracy: 0.5
Final Score: 0.5
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.50      0.60      0.55         5

    accuracy                           0.50        10
   macro avg       0.50      0.50      0.49        10
weighted avg       0.50      0.50      0.49        10

In [187]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X = tfidf_matrix.toarray()  # Convert sparse matrix to dense array
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model_if = LogisticRegression()
model_if.fit(X_train, y_train)

LogisticRegression()

In [188]:
predict = model_if.predict(X_test)

accuracy = model_if.score(X_test, y_test)

final_score = accuracy_score(y_test, model_if.predict(X_test))
print("Accuracy:", accuracy)
print("Final Score:", final_score)
print("Classification Report:\n", classification_report(y_test, model_if.predict(X_test)))

Accuracy: 0.6
Final Score: 0.6
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.20      0.33         5
           1       0.56      1.00      0.71         5

    accuracy                           0.60        10
   macro avg       0.78      0.60      0.52        10
weighted avg       0.78      0.60      0.52        10